version: '3.3'

networks:
    internalNet:
        internal: true
    localNet:
        external: true

services:
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - internalNet
            - localNet

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'santorenzdb'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - 3306:3306
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        networks:
            - internalNet
            - localNet
